// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAN-2b51En8lzVEfCUAvNxgY4F9HRq1XS4',
    appId: '1:723568831052:web:a865550e50980d613f62e9',
    messagingSenderId: '723568831052',
    projectId: 'campusone-c3c71',
    authDomain: 'campusone-c3c71.firebaseapp.com',
    storageBucket: 'campusone-c3c71.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgqgsTkRRDsXqKhJ1INuvcewUZ8ZQ5BBY',
    appId: '1:723568831052:android:eda729075eb681b93f62e9',
    messagingSenderId: '723568831052',
    projectId: 'campusone-c3c71',
    storageBucket: 'campusone-c3c71.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUTBFS9VMR9dZM9FXWiNhBwSx8s5rCwvQ',
    appId: '1:723568831052:ios:4224303081566e803f62e9',
    messagingSenderId: '723568831052',
    projectId: 'campusone-c3c71',
    storageBucket: 'campusone-c3c71.firebasestorage.app',
    iosClientId: '723568831052-53b6irer1f7qvhp50ertkm3vcdb57ccl.apps.googleusercontent.com',
    iosBundleId: 'com.campusone.app.campusone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUTBFS9VMR9dZM9FXWiNhBwSx8s5rCwvQ',
    appId: '1:723568831052:ios:4224303081566e803f62e9',
    messagingSenderId: '723568831052',
    projectId: 'campusone-c3c71',
    storageBucket: 'campusone-c3c71.firebasestorage.app',
    iosClientId: '723568831052-53b6irer1f7qvhp50ertkm3vcdb57ccl.apps.googleusercontent.com',
    iosBundleId: 'com.campusone.app.campusone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAN-2b51En8lzVEfCUAvNxgY4F9HRq1XS4',
    appId: '1:723568831052:web:8d11c449db474b613f62e9',
    messagingSenderId: '723568831052',
    projectId: 'campusone-c3c71',
    authDomain: 'campusone-c3c71.firebaseapp.com',
    storageBucket: 'campusone-c3c71.firebasestorage.app',
  );
}
